comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
      tests:
        paths:
          - "tests/"
          - "longtests/"
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
